AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 125
  AllowedPatterns:
    - 'raise'

Naming/RescuedExceptionsVariableName:
  Enabled: false # conflicts with reek expectations
Metrics/ClassLength:
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
