AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Naming/RescuedExceptionsVariableName:
  Enabled: false # conflicts with reek expectations

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
